
/* Autogenerated by /usr/bin/instcomp on Tue May 16 23:10:54 2017 -- do not edit */

#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "hal_priv.h"
#include "hal_accessor.h"
#include "hal_internal.h"

static int comp_id;


static char *compname = "pp_gpio";

#ifdef MODULE_INFO
MODULE_INFO(machinekit, "component:pp_gpio:Raspberry PI digital output for Machinekit via pigpio library");
MODULE_INFO(machinekit, "pin:##.input:bit:pincount:out::None");
MODULE_INFO(machinekit, "pin:##.output:bit:pincount:in::None");
MODULE_INFO(machinekit, "pin:##.invert:bit:pincount:io::None");
MODULE_INFO(machinekit, "pin:##.dowrite:bit:pincount:io::1");
MODULE_INFO(machinekit, "pin:##.pinmode:u32:pincount:io::0");
MODULE_INFO(machinekit, "pin:##.bcm:u32:pincount:io::None");
MODULE_INFO(machinekit, "pin:##.pud:u32:pincount:io::0");
MODULE_INFO(machinekit, "pin:pi_instance:u32:None:io::None");
MODULE_INFO(machinekit, "instanceparam:pincount:int::28");
MODULE_INFO(machinekit, "license:GPL");
MODULE_INFO(machinekit, "author:Brian Schousek");
MODULE_INFO(machinekit, "funct:_:1:");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO
RTAPI_TAG(HAL,HC_INSTANTIABLE);


#define MAXCOUNT 28
#define DEFAULTCOUNT 28

static int pincount = 28;
RTAPI_IP_INT(pincount, "");

struct inst_data
    {
    hal_bit_t *_input[28];
    hal_bit_t *_output[28];
    hal_bit_t *_invert[28];
    hal_bit_t *_dowrite[28];
    hal_u32_t *_pinmode[28];
    hal_u32_t *_bcm[28];
    hal_u32_t *_pud[28];
    hal_u32_t *pi_instance;
    int local_argc;
    char **local_argv;
    int local_pincount;
    };

static int maxpins __attribute__((unused)) = 28;
static int pp_gpio_(void *arg, const hal_funct_args_t *fa);

static int instantiate(const int argc, const char**argv);

static int delete(const char *name, void *inst, const int inst_size);

static int extra_inst_setup(struct inst_data* ip, const char *name, int argc, const char**argv);

#undef TRUE
#undef FALSE
#undef true
#define true (1)
#undef false
#define false (0)

static int export_halobjs(struct inst_data *ip, int owner_id, const char *name, const int argc, const char **argv)
{
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int j __attribute__((unused)) = 0;
    int z __attribute__((unused)) = 0;
    z = pincount;
    if(z > maxpins)
       z = maxpins;
    for(j=0; j < z; j++)
        {
        r = hal_pin_bit_newf(HAL_OUT, &(ip->_input[j]), owner_id,
            "%s.%02d.input", name, j);
        if(r != 0) return r;
        }

    z = pincount;
    if(z > maxpins)
       z = maxpins;
    for(j=0; j < z; j++)
        {
        r = hal_pin_bit_newf(HAL_IN, &(ip->_output[j]), owner_id,
            "%s.%02d.output", name, j);
        if(r != 0) return r;
        }

    z = pincount;
    if(z > maxpins)
       z = maxpins;
    for(j=0; j < z; j++)
        {
        r = hal_pin_bit_newf(HAL_IO, &(ip->_invert[j]), owner_id,
            "%s.%02d.invert", name, j);
        if(r != 0) return r;
        }

    z = pincount;
    if(z > maxpins)
       z = maxpins;
    for(j=0; j < z; j++)
        {
        r = hal_pin_bit_newf(HAL_IO, &(ip->_dowrite[j]), owner_id,
            "%s.%02d.dowrite", name, j);
        if(r != 0) return r;
            *(ip->_dowrite[j]) = 1;
        }

    z = pincount;
    if(z > maxpins)
       z = maxpins;
    for(j=0; j < z; j++)
        {
        r = hal_pin_u32_newf(HAL_IO, &(ip->_pinmode[j]), owner_id,
            "%s.%02d.pinmode", name, j);
        if(r != 0) return r;
            *(ip->_pinmode[j]) = 0;
        }

    z = pincount;
    if(z > maxpins)
       z = maxpins;
    for(j=0; j < z; j++)
        {
        r = hal_pin_u32_newf(HAL_IO, &(ip->_bcm[j]), owner_id,
            "%s.%02d.bcm", name, j);
        if(r != 0) return r;
        }

    z = pincount;
    if(z > maxpins)
       z = maxpins;
    for(j=0; j < z; j++)
        {
        r = hal_pin_u32_newf(HAL_IO, &(ip->_pud[j]), owner_id,
            "%s.%02d.pud", name, j);
        if(r != 0) return r;
            *(ip->_pud[j]) = 0;
        }

    r = hal_pin_u32_newf(HAL_IO, &(ip->pi_instance), owner_id,
            "%s.pi-instance", name);
    if(r != 0) return r;


// if not set by instantiate() set to default
    if(! ip->local_pincount || ip->local_pincount == -1)
         ip->local_pincount = DEFAULTCOUNT;

    hal_print_msg(RTAPI_MSG_DBG,"export_halobjs() ip->local_pincount set to %d", ip->local_pincount);


    ip->local_argv = halg_dupargv(1, argc, argv);

    ip->local_argc = argc;


    // exporting an extended thread function:
    hal_export_xfunct_args_t __xf = 
        {
        .type = FS_XTHREADFUNC,
        .funct.x = pp_gpio_,
        .arg = ip,
        .uses_fp = 1,
        .reentrant = 0,
        .owner_id = owner_id
        };

    rtapi_snprintf(buf, sizeof(buf),"%s.funct", name);
    r = hal_export_xfunctf(&__xf, buf, name);
    if(r != 0)
        return r;
    return 0;
}

// constructor - init all HAL pins, funct etc here
static int instantiate(const int argc, const char**argv)
{
struct inst_data *ip;
// argv[0]: component name
const char *name = argv[1];
int r;
int k;

// allocate a named instance, and some HAL memory for the instance data
int inst_id = hal_inst_create(name, comp_id, sizeof(struct inst_data), (void **)&ip);

    if (inst_id < 0)
        return -1;

// here ip is guaranteed to point to a blob of HAL memory of size sizeof(struct inst_data).
    hal_print_msg(RTAPI_MSG_DBG,"%s inst=%s argc=%d",__FUNCTION__, name, argc);

// Debug print of params and values
    hal_print_msg(RTAPI_MSG_DBG,"%s: int instance param: %s=%d",__FUNCTION__,"pincount", pincount);
//  if pincount=NN is passed, set local variable here, if not set to default
    int pin_param_value = pincount;
    if((pin_param_value == -1) || (pin_param_value == 0))
        pin_param_value = DEFAULTCOUNT;
    else if((pin_param_value > 0) && (pin_param_value > MAXCOUNT))
        pin_param_value = MAXCOUNT;
    ip->local_pincount = pincount = pin_param_value;
    hal_print_msg(RTAPI_MSG_DBG,"ip->local_pincount set to %d", pin_param_value);

// These pins - pin_ptrs- functs will be owned by the instance, and can be separately exited with delinst
    r = export_halobjs(ip, inst_id, name, argc, argv);
    // if the extra_inst_setup returns non zero will abort module creation
    k = extra_inst_setup(ip, name, argc, argv);
    if(k != 0)
        return k;

//reset pincount to -1 so that instantiation without it will result in DEFAULTCOUNT
    pincount = -1;

    return r;
}

int rtapi_app_main(void)
{
    comp_id = hal_xinit(TYPE_RT, 0, 0, instantiate, delete, compname);

    if (comp_id < 0)

        return -1;

    hal_ready(comp_id);

    return 0;
}

void rtapi_app_exit(void)
{
    hal_exit(comp_id);
}

// Custom destructor - delete()
// pins, pin_ptrs, and functs are automatically deallocated regardless if a
// destructor is used or not (see below)
//
// Some objects like vtables, rings, threads are not owned by a component
// interaction with such objects may require a custom destructor for
// cleanup actions
// Also allocated memory that hal_lib will know nothing about ie local_argv
//
// NB: if a customer destructor is used, it is called
// - after the instance's functs have been removed from their respective threads
//   (so a thread funct call cannot interact with the destructor any more)
// - any pins and params of this instance are still intact when the destructor is
//   called, and they are automatically destroyed by the HAL library once the
//   destructor returns


static int delete(const char *name, void *inst, const int inst_size)
{

    struct inst_data *ip = inst;

    HALDBG("Entering delete() : inst=%s size=%d %p local_argv = %p\n", name, inst_size, inst, ip->local_argv);

    HALDBG("Before free ip->local_argv[0] = %s\n", ip->local_argv[0]);

   	halg_free_argv(1, ip->local_argv);

    HALDBG("Now ip->local_argv[0] = %s\n", ip->local_argv[0]);

    return 0;

}


#undef FUNCTION
#define FUNCTION(name) static int pp_gpio_(void *arg, const hal_funct_args_t *fa)
// if the extra_inst_setup returns non zero it will abort the module creation
#undef EXTRA_INST_SETUP
#define EXTRA_INST_SETUP() static int extra_inst_setup(struct inst_data *ip, const char *name, int argc, const char**argv)
#undef fperiod
#define fperiod (period * 1e-9)
#undef _input
#define _input(i) (*(ip->_input[i]))
#undef _output
#define _output(i) (0+*(ip->_output[i]))
#undef _invert
#define _invert(i) (*(ip->_invert[i]))
#undef _dowrite
#define _dowrite(i) (*(ip->_dowrite[i]))
#undef _pinmode
#define _pinmode(i) (*(ip->_pinmode[i]))
#undef _bcm
#define _bcm(i) (*(ip->_bcm[i]))
#undef _pud
#define _pud(i) (*(ip->_pud[i]))
#undef pi_instance
#define pi_instance (*ip->pi_instance)
#undef local_pincount
#define local_pincount (ip->local_pincount)
#undef local_argc
#define local_argc (ip->local_argc)
#undef local_argv
#define local_argv(i) (ip->local_argv[i])


#line 31 "pp_gpio.icomp"
#include <pigpiod_if2.h>

FUNCTION(_) {
long period __attribute__((unused)) = fa_period(fa);
struct inst_data *ip __attribute__((unused)) = arg;

	int i;
	unsigned mytemp;

	for (i=0 ; i < local_pincount ; i++) {
		set_mode(pi_instance, _bcm(i), _pinmode(i));
		set_pull_up_down(pi_instance, _bcm(i), _pud(i));
		if (_pinmode(i) == 0) {

			mytemp= gpio_read(pi_instance, _bcm(i));
			if (_invert(i)) mytemp=!mytemp;
			_input(i)=mytemp;
			
		}
		else {
			
			mytemp=_output(i);
			if (_invert(i)) mytemp=!mytemp;
			_input(i)=mytemp;
			if (_dowrite(i)) {
				gpio_write(pi_instance, _bcm(i), mytemp);
				}
			}
		}
	


	
	return 0;

}

EXTRA_INST_SETUP(){
	

	char host[]="moby.local";
	char port[]="8888";
	pi_instance=pigpio_start(host,port);
	

	
 

}

// EXTRA_INST_CLEANUP(){
// 	pigpio_stop(pi_instance);

// }


